
INSERT INTO `training_type_lang` (`id`, `title`, `training_type_id`, `explanation`, `extra_comment`, `created_by`, `created_at`, `updated_by`, `updated_at`, `language`) VALUES
(40, '90\' en endurance I2, intégrer 5*[1\' I3 avec un peu plus de résistance musculaire], 10\' easy (bien mouliner) et par la suite 3*[20\'\' sprints (10\'\' lancer en danseuse et ensuite 10\'\' assis vite...) I3-I4 - P1\'30\'\' en moulinant]', 40, 'Bien respirer (avec le ventre), bien décontracté au niveau du haut du corps. Mettre le tonus parfait dans les jambes. Evidémment, ces séances de pré-competition sont aussi une préparation psychique et un dernier check matériel', NULL, NULL, NULL, NULL, NULL, 'fr-CH'),
(41, '15\' endurance I2. Faire 4 accélérations de 100m à 90% de la vitesse maximale (belle technique, bien posé) - P2\' I1, 4\' I3 (belle technique, bien posé également), 20\' I2', 41, 'Il s\'agit de te préparer parfaitement pour la compétition qui a lieu le lendemain. Les accélérations et le petit bloc en I3 te mettent en condition physique idéale. Les muscles sont au top et durant cette journée de pré-compétition, tu as aussi le temps de te préparer idéalement au niveau du psychique et de préparer tout ton matériel nécessaire', 'Ton programme nutrition est également parfaitement en place. Le petit document de ma part peut t\'aider si tu veux', NULL, NULL, NULL, NULL, 'fr-CH'),
(42, 'Programme par l\'instructrice.', 42, 'Ces entraînements de gainage se complètent de manière parfaite avec les sports d\'endurance de la semaine.', '', NULL, NULL, NULL, NULL, 'fr-CH'),
(43, 'Journée de repos', 43, 'La récupération doit faire partie intégrante de la préparation physique. Elle est tout aussi importante que l’entraînement lui-même et peut se faire de nombreuses manières.', '', NULL, NULL, NULL, NULL, 'fr-CH'),
(44, 'Force en salle privé', 44, 'Fais un joli mix purement musculaire (pas de vélo rouleau). Du TRX, du Sypoba, des Kettlebell, un joli programme gainage. ', 'Une météo pas terrible donc parfait de faire une belle séance dans ta salle de torture préférée !', NULL, NULL, NULL, NULL, 'fr-CH'),
(45, 'Devenir Mikael Phelps', 45, 'Fixe toi tout simplement un but de distance et fais des séries bien variées (des 25m, des 50, des 100m, des 400m). N\'hésite pas d\'utiliser un peu du matériel (planche, pool boye, etc).', 'Je me réjouis aussi là de faire des séances trop geil !', NULL, NULL, NULL, NULL, 'fr-CH'),
(46, 'Yoga', 46, 'C\'est pas moi qui va te donner des explications comment faire le "Yoga dans la chambre" ;)', 'Cela doit faire un grand bien quand même ;)', NULL, NULL, NULL, NULL, 'fr-CH'),
(47, 'Escalade - tennis - badminton - squash - inline - ... ', 47, 'Quitter les sports "diagonales". Ludique, amusement, explosif, coordinatif. ', '90\' FUN ! Une option aujourd\'hui, c\'est aussi de faire une journée de repos complète !', NULL, NULL, NULL, NULL, 'fr-CH');
