<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'City Done' => '',
    'City Edit' => '',
    'Danger' => '',
    'Default' => '',
    'Info' => '',
    'Missing "returnFullPath" for "{item}" in {behavior} and no default "returnFullPath" is set.' => '',
    'Missing "skipOnEmpty" for "{item}" in {behavior} and no default "skipOnEmpty" is set.' => '',
    'Missing path for "{item}" in {behavior} and no default path is set.' => '',
    'Planned' => '',
    'Please specify array of available languages for the {behavior} in the {owner} or in the application parameters' => '',
    'Please specify langForeignKey for the {behavior} in the {owner}' => '',
    'Please specify multilingual attributes for the {behavior} in the {owner}' => '',
    'Please specify multilingual langClassName for the {behavior} in the {owner}' => '',
    'Primary' => '',
    'Success' => '',
    'The "fileNameAttributes" must be set. No file validation rules() found in your model. like: [[\'image\',\'image2\'], \'file\', \'extensions\' => \'jpg\'] or set it manually for "{behavior}"' => '',
    'Warning' => '',
    '{owner} must have a primary key.' => '',
    'Actif' => 'Actif',
    'Archived' => 'Archivé',
    'Draft' => 'Brouillon',
    'No' => 'Non',
    'Order Updated on {date}' => 'Ordre mis à jour le {date}',
    'The requested {modelName} does not exists.' => 'Le modèle {modelName} n\'existe pas',
    'Validate' => 'En Validation',
    'Yes' => 'Oui',
    'the "{name}" must be an array for "{class}".' => 'l\'attribut "{name}" doit être une "array" pour "{class}"',
    'the "{name}" must be set for "{class}".' => 'l\'attribut "{name}" doit être renseigné pour "{class}"',
];
