<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Click on the following link to see your planning:' => 'Clique le lien ci-dessous pour le consulter:',
    'Your new planning for the following days:' => 'Nouveau planning pour les jours suivants:',
    'Hi {name},' => 'Salut {name},',
    'See planning' => 'Voir ton planning',
    'Your objectif: {word_of_the_week}' => 'Ton objectif: {word_of_the_week}',
    'Welcome on {sitename}' => 'Bienvenue sur {sitename}',
];
